api: Implement state diff
rvolosatovs/turtlitto pull request #107
Opened 2018-06-14 13:26 UTC by Desahri

Includes a test

2018-06-14 13:38 UTC, helaan commented
Hmm, this PR is a bit limited: you could also just send the properties that changed, which would save even more bandwidth.
Example: If the `batteryStatus` property changes of turtle 1, you can just send `{"turtles"{"1":{"batteryStatus":99}}}`

2018-06-14 13:46 UTC, rvolosatovs requested changes

2018-06-14 13:46 UTC, rvolosatovs commented on pkg/api/api.go
> +func turtleStateIsSame(ts1, ts2 *TurtleState) bool {
This function is not needed, you can simply use `reflect.DeepEqual`

2018-06-14 13:46 UTC, rvolosatovs commented on pkg/api/api.go
> +//returns a turtleState mapping which contains only the turtleState of the turtles of which the old state is different from the new state
`// StateDifference ...`

2018-06-14 13:46 UTC, rvolosatovs commented on pkg/api/api.go
> +func StateDifference(turtlesOld, turtlesNew map[string]*TurtleState) map[string]*TurtleState {
Call it `StateDiff`

2018-06-14 13:50 UTC, rvolosatovs commented
As we discussed with @Huubvr earlier, it should be done in a following way:
1. Marshal both states into `map[string]interface{}` recursively https://godoc.org/github.com/fatih/structs#Map
2. Compute diff of these maps(recursively)
3. Find a way to go back from map to the state struct. Maybe we can marshal the map to json and the unmarshal the json into the state.

2018-06-15 08:16 UTC, golangci commented on pkg/api/api_test.go
> +	"github.com/rvolosatovs/turtlitto/pkg/api/apitest"
File is not goimports-ed

2018-06-15 09:06 UTC, rvolosatovs requested changes

2018-06-15 09:06 UTC, rvolosatovs commented on pkg/api/api_test.go
> +			expectedOutputState: &State{},
This has to be `nil`

2018-06-15 09:07 UTC, rvolosatovs commented on pkg/api/api_test.go
> +						Kinect1State:    KinectStateBall,
For this test case add some field, which is included in the `old` struct, but not defined in the `new`, to make sure it's not removed.

2018-06-15 09:09 UTC, rvolosatovs commented on pkg/api/api.go
> +		if reflect.DeepEqual(old[k], new[k]) { //if there is a difference in the turtle state
This comment is not required and does not make too much sense, given that this function does not know anything about turtle states

2018-07-03 11:05 UTC, closed without merging